name: linux
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check 
        run: ls
      - name: configure 
        run: cmake .
      - name: build
        run: make
      - name: tests
        run: ./benchmark
